### PR TITLE
New art

### PR DESCRIPTION
**Pull request by f4rukyldrm**
Created ubuntu terminal in css

### CODE REVIEW

**Review by VulcanWM — APPROVED** [review]
This is cool, thanks!
Which repl do you want me to tip?

**Comment by f4rukyldrm** [comment]
> This is cool, thanks! Which repl do you want me to tip?

You are welcome. You can tip on whichever repl you like they are course projects anyways.

**Comment by VulcanWM** [comment]
tipped! thanks for your help

**Comment by f4rukyldrm** [comment]
Hi is it normal that I still didn't get the tip?

**Comment by VulcanWM** [comment]
Check now…

**Comment by f4rukyldrm** [comment]
Thanks I got it

**Pull request merged**
